export default {
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR',
    SIGNOUT_SUCCESS: 'SIGNOUT_SUCCESS',
    SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
    SIGNUP_ERROR: 'SIGNUP_ERROR',
    CREATE_AUTO_SUCCESS: 'CREATE_AUTO_SUCCESS',
    CREATE_AUTO_ERROR: 'CREATE_AUTO_ERROR',
    EDIT_AUTO_SUCCESS: 'EDIT_AUTO_SUCCESS',
    EDIT_AUTO_ERROR: 'EDIT_AUTO_ERROR',
    DELETE_AUTO_SUCCESS: 'DELETE_AUTO_SUCCESS',
    DELETE_AUTO_ERROR: 'DELETE_AUTO_ERROR'
  }