const EV_EDIT_CLICKED='EV_EDIT_CLICKED';
const EV_DEL_CLICKED='EV_DEL_CLICKED';
const EV_ADDNEW_CLICKED='EV_ADDNEW_CLICKED';
const EV_ROW_CLICKED='EV_ROW_CLICKED';
const EV_CLIENT_SAVE='EV_CLIENT_SAVE';
const EV_CANCEL_EDIT='EV_CANCEL_EDIT';
const EV_CLIENT_EDIT_SAVE='EV_CLIENT_EDIT_SAVE';
const EV_CHANGE_COMPANY='EV_CHANGE_COMPANY';
const EV_FILTER_CLIENTS='EV_FILTER_CLIENTS';



export {
    EV_EDIT_CLICKED,
    EV_DEL_CLICKED,
    EV_ADDNEW_CLICKED,
    EV_ROW_CLICKED,
    EV_CLIENT_SAVE,
    EV_CANCEL_EDIT,
    EV_CLIENT_EDIT_SAVE,
    EV_CHANGE_COMPANY,
    EV_FILTER_CLIENTS,
  }